from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    args = [
        DeclareLaunchArgument('depth_topic', default_value='/camera/depth/image_raw'),
        DeclareLaunchArgument('odom_topic', default_value='/odom_combined'),
        DeclareLaunchArgument('input_cmd_vel_topic', default_value='/cmd_vel_raw'),
        DeclareLaunchArgument('output_cmd_vel_topic', default_value='/cmd_vel'),
        DeclareLaunchArgument('status_topic', default_value='/depth_camera/obstacle_status'),
        DeclareLaunchArgument('dry_run', default_value='true'),
        DeclareLaunchArgument('allow_bypass', default_value='false'),
        DeclareLaunchArgument('use_fused_pose_bypass', default_value='false'),
        DeclareLaunchArgument('danger_distance_m', default_value='0.55'),
        DeclareLaunchArgument('clear_distance_m', default_value='0.80'),
        DeclareLaunchArgument('front_invalid_depth_block_fraction', default_value='0.35'),
        DeclareLaunchArgument('side_invalid_depth_block_fraction', default_value='0.90'),
        DeclareLaunchArgument('invalid_depth_block_fraction', default_value='-1.0'),
        DeclareLaunchArgument('publish_period_s', default_value='0.10'),
        DeclareLaunchArgument('depth_timeout_s', default_value='0.50'),
        DeclareLaunchArgument('cmd_timeout_s', default_value='0.50'),
        DeclareLaunchArgument('odom_timeout_s', default_value='0.50'),
        DeclareLaunchArgument('depth_process_period_s', default_value='0.10'),
        DeclareLaunchArgument('bypass_angular_z', default_value='0.25'),
        DeclareLaunchArgument('return_angular_z', default_value='0.25'),
        DeclareLaunchArgument('return_heading_angular_sign', default_value='-1.0'),
        DeclareLaunchArgument('max_forward_mps', default_value='0.40'),
        DeclareLaunchArgument('normal_forward_mps', default_value='0.40'),
        DeclareLaunchArgument('bypass_forward_mps', default_value='0.20'),
        DeclareLaunchArgument('bypass_forward_distance_m', default_value='0.50'),
        DeclareLaunchArgument('return_heading_tolerance_rad', default_value='0.08'),
        DeclareLaunchArgument('line_return_tolerance_m', default_value='0.08'),
        DeclareLaunchArgument('reacquire_forward_mps', default_value='0.10'),
        DeclareLaunchArgument('reacquire_angular_z', default_value='0.20'),
        DeclareLaunchArgument('reacquire_max_yaw_rad', default_value='1.5708'),
        DeclareLaunchArgument('avoid_min_forward_s', default_value='1.00'),
        DeclareLaunchArgument('side_clear_hold_s', default_value='1.00'),
        DeclareLaunchArgument('exit_forward_hold_s', default_value='0.50'),
        DeclareLaunchArgument('pose_stall_timeout_s', default_value='1.00'),
        DeclareLaunchArgument('pose_stall_distance_epsilon_m', default_value='0.02'),
        DeclareLaunchArgument('pose_stall_yaw_epsilon_rad', default_value='0.03'),
    ]

    node = Node(
        package='depth_camera_perception',
        executable='obstacle_guard',
        name='depth_obstacle_guard',
        output='screen',
        parameters=[
            {
                'depth_topic': LaunchConfiguration('depth_topic'),
                'odom_topic': LaunchConfiguration('odom_topic'),
                'input_cmd_vel_topic': LaunchConfiguration('input_cmd_vel_topic'),
                'output_cmd_vel_topic': LaunchConfiguration('output_cmd_vel_topic'),
                'status_topic': LaunchConfiguration('status_topic'),
                'dry_run': LaunchConfiguration('dry_run'),
                'allow_bypass': LaunchConfiguration('allow_bypass'),
                'use_fused_pose_bypass': LaunchConfiguration('use_fused_pose_bypass'),
                'danger_distance_m': LaunchConfiguration('danger_distance_m'),
                'clear_distance_m': LaunchConfiguration('clear_distance_m'),
                'front_invalid_depth_block_fraction': LaunchConfiguration('front_invalid_depth_block_fraction'),
                'side_invalid_depth_block_fraction': LaunchConfiguration('side_invalid_depth_block_fraction'),
                'invalid_depth_block_fraction': LaunchConfiguration('invalid_depth_block_fraction'),
                'publish_period_s': LaunchConfiguration('publish_period_s'),
                'depth_timeout_s': LaunchConfiguration('depth_timeout_s'),
                'cmd_timeout_s': LaunchConfiguration('cmd_timeout_s'),
                'odom_timeout_s': LaunchConfiguration('odom_timeout_s'),
                'depth_process_period_s': LaunchConfiguration('depth_process_period_s'),
                'bypass_angular_z': LaunchConfiguration('bypass_angular_z'),
                'return_angular_z': LaunchConfiguration('return_angular_z'),
                'return_heading_angular_sign': LaunchConfiguration('return_heading_angular_sign'),
                'max_forward_mps': LaunchConfiguration('max_forward_mps'),
                'normal_forward_mps': LaunchConfiguration('normal_forward_mps'),
                'bypass_forward_mps': LaunchConfiguration('bypass_forward_mps'),
                'bypass_forward_distance_m': LaunchConfiguration('bypass_forward_distance_m'),
                'return_heading_tolerance_rad': LaunchConfiguration('return_heading_tolerance_rad'),
                'line_return_tolerance_m': LaunchConfiguration('line_return_tolerance_m'),
                'reacquire_forward_mps': LaunchConfiguration('reacquire_forward_mps'),
                'reacquire_angular_z': LaunchConfiguration('reacquire_angular_z'),
                'reacquire_max_yaw_rad': LaunchConfiguration('reacquire_max_yaw_rad'),
                'avoid_min_forward_s': LaunchConfiguration('avoid_min_forward_s'),
                'side_clear_hold_s': LaunchConfiguration('side_clear_hold_s'),
                'exit_forward_hold_s': LaunchConfiguration('exit_forward_hold_s'),
                'pose_stall_timeout_s': LaunchConfiguration('pose_stall_timeout_s'),
                'pose_stall_distance_epsilon_m': LaunchConfiguration('pose_stall_distance_epsilon_m'),
                'pose_stall_yaw_epsilon_rad': LaunchConfiguration('pose_stall_yaw_epsilon_rad'),
            }
        ],
    )

    return LaunchDescription(args + [node])
